### ISSUE TITLE
OOmph fails "No repository found webtools/CI/3.28.0"

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#83]
I tried to OOmph eclipse with the link given in https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md
result:

`ERROR: org.eclipse.equinox.p2.metadata.repository code=1000 No repository found at https://download.eclipse.org/webtools/CI/3.28.0/I-latest/repository.`

@merks any idea?

```
Executing bootstrap tasks
OpenJDK Runtime Environment 17.0.4.1+1
Product org.eclipse.applications.eclipse.platform.sdk.latest
Workspace C:\Users\jkubitz\platform-sdk9\latestRelease platformWs
Project org.eclipse.equinox.core.master
Project org.eclipse.equinox.p2.master
Project org.eclipse.equinox.binaries.master
Project org.eclipse.jdt.features.master
Project org.eclipse.jdt.core.master
Project org.eclipse.jdt.debug.master
Project org.eclipse.jdt.ui.master
Project org.eclipse.jdt.core.tests.master
Project org.eclipse.jdt.core.testbinaries.master
Project org.eclipse.jdt.debug.tests.master
Project org.eclipse.jdt.ui.tests.master
Project org.eclipse.jdt.ui.examples.master
Project org.eclipse.pde.master
Project org.eclipse.platform.platform.master
Project org.eclipse.platform.debug.master
Project org.eclipse.platform.dependencies.ecf.master
Project org.eclipse.platform.dependencies.emf.master
Project org.eclipse.platform.documentation.master
Project org.eclipse.platform.images.master
Project org.eclipse.platform.news.master
Project org.eclipse.platform.swt.master
Project org.eclipse.platform.swt.website.master
Project org.eclipse.platform.text.master
Project org.eclipse.platform.ua.master
Project org.eclipse.platform.ui.master
Project org.eclipse.platform.ui.tools.master
Project org.eclipse.platform.releng.master
Project org.eclipse.platform.releng.aggregator.master
Project org.eclipse.platform.releng.buildtools.master
Project org.eclipse.platform.website.master
Bundle org.eclipse.oomph.setup 1.25.0.v20220914-1119, build=5729, branch=e3a48095495b13551e05eca4aaee5945806274ab
Bundle org.eclipse.oomph.setup.core 1.26.0.v20221125-1553, build=5729, branch=e3a48095495b13551e05eca4aaee5945806274ab
Bundle org.eclipse.oomph.setup.installer 1.27.0.v20221118-0749, build=5729, branch=e3a48095495b13551e05eca4aaee5945806274ab
Bundle org.eclipse.oomph.setup.p2 1.19.0.v20220607-1104, build=5729, branch=e3a48095495b13551e05eca4aaee5945806274ab
Performing Workspace C:\Users\jkubitz\platform-sdk9\latestRelease platformWs
Performing P2 Director (Eclipse SDK (4.27 - 2023-03) + Platform + SWT Tools + EMF Tools + E4 Tools + CBI Aggregator + m2e)
Offline = false
Mirrors = true
Resolving 22 requirements from 8 repositories to C:\Users\jkubitz\platform-sdk9\eclipse
Requirement org.eclipse.equinox.p2.iu:org.eclipse.platform.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.jdt.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.pde.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.sdk.ide [4.27.0,5.0.0) (filter=(|(&(osgi.arch=aarch64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=aarch64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=ppc64le)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=x86_64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=x86_64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=win32)(osgi.ws=win32))))
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.targlets.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.targlets.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.pde.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.jdt.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.git.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.egit.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.workingsets.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.pde.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.lemminx.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.cbi.p2repo.aggregator.editor.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.cbi.p2repo.aggregator.analyzer.editor.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.e4.core.tools.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.emf.ecore.editor.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.emf.codegen.ecore.ui.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.swt.tools.feature.feature.group
Requirement org.eclipse.equinox.p2.iu:org.eclipse.jdt.junit4.runtime
Repository https://download.eclipse.org/eclipse/updates/4.27-I-builds
Repository https://download.eclipse.org/oomph/updates/milestone/latest
Repository https://download.eclipse.org/modeling/emf/emf/builds/release/2.32
Repository https://download.eclipse.org/egit/updates
Repository https://download.eclipse.org/technology/m2e/snapshots/latest
Repository https://download.eclipse.org/webtools/CI/3.28.0/I-latest/repository
Repository https://download.eclipse.org/cbi/updates/p2-aggregator/tools/nightly/latest
Repository https://download.eclipse.org/modeling/emf/emf/builds/nightly/latest
Adding repository https://download.eclipse.org/cbi/updates/p2-aggregator/tools/nightly/latest
Adding repository https://download.eclipse.org/modeling/emf/emf/builds/release/2.32
Adding repository https://download.eclipse.org/webtools/CI/3.28.0/I-latest/repository
Adding repository https://download.eclipse.org/modeling/emf/emf/builds/nightly/latest
Adding repository https://download.eclipse.org/technology/m2e/snapshots/latest
Adding repository https://download.eclipse.org/egit/updates
Adding repository https://download.eclipse.org/eclipse/updates/4.27-I-builds
Adding repository https://download.eclipse.org/oomph/updates/milestone/latest
ERROR: org.eclipse.equinox.p2.metadata.repository code=1000 No repository found at https://download.eclipse.org/webtools/CI/3.28.0/I-latest/repository.
  at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:405)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:119)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:386)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:277)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:518)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$RepositoryLoader$Worker.perform(ProfileTransactionImpl.java:1615)
  at org.eclipse.oomph.util.WorkerPool$Worker.run(WorkerPool.java:437)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Took 4 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.

```

**Comment by iloveeclipse** [comment]
I've noticed that too by manual update, the old https://download.eclipse.org/webtools/CI/3.28.0/I-latest/repository repo is removed, new one https://download.eclipse.org/webtools/CI/3.28.0/I-latest/repository should be used.

See https://github.com/eclipse-platform/eclipse.platform.ui/commit/b7fe4bcc3f7c77f27303401979bee98a86c6b767

**Comment by jukzi** [comment]
Hi Andrey, happy new year. What has to be done that the Oomph setup works? It still does not.

**Comment by iloveeclipse** [comment]
Yep, happy new year too :-)
It begins as usually: [broken SDK build](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/790), broken tooling :-)

Fixed via https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/792

**Comment by jukzi** [comment]
as it still does not work .. do i have to wait till next i-build now?

**Comment by iloveeclipse** [comment]
> as it still does not work .. do i have to wait till next i-build now?

If you have releng aggregator repo updated and can see my commit locally, I would guess yes. 
I honestly just did `git grep webtools` and fixed one place where I've suspected the problem. 

May be Oomph uses tags to checkout latest "officially built" commit, I have no idea.
@merks ?

**Comment by merks** [comment]
The build worked

https://ci.eclipse.org/oomph/job/setup-archiver/39261/

It shows this:
```
PROMOTING changes to /home/data/httpd/download.eclipse.org/oomph/www/setups.zip
NO FAILURES
CHANGED! https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/Platform.setup
diff -ar setups-old/https/raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/Platform.setup setups-new/https/raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/Platform.setup
838c838
< url="https://download.eclipse.org/webtools/CI/3.28.0/I-latest/repository"/>
---
> url="https://download.eclipse.org/webtools/CI/3.29.0/I-latest/repository"/>
```
Now there could be another short delay before https://www.eclipse.org/setups/setup.zip actually serves the new content instead of a previously cached version.

**Comment by jukzi** [comment]
thanks, now it worked.
