### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by GTIAM** [eclipse-platform/.github#90]
Hi,

When we try to launch Eclipse, we have this error : EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbcf828a10, pid=7184, tid=10808

We uninstall all jdk/jre ; delete all eclipse folder. We just download the last version of eclipse 2022-12 with embedded OpenJDK Runtime Environment Temurin-17.0.4.1+1.

When we try to install eclipse we have the same error asking us to report the bug here:

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbcf828a10, pid=7184, tid=10808

 JRE version: OpenJDK Runtime Environment Temurin-17.0.4.1+1 (17.0.4.1+1) (build 17.0.4.1+1)
 Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (17.0.4.1+1, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
 Problematic frame:
 V  [jvm.dll+0x368a10]

 No core dump will be written. Minidumps are not enabled by default on client versions of Windows

 If you would like to submit a bug report, please visit:
   https://github.com/adoptium/adoptium-support/issues
[hs_err_pid7184.log](https://github.com/eclipse-platform/.github/files/10706848/hs_err_pid7184.log)
[replay_pid7184.log](https://github.com/eclipse-platform/.github/files/10706849/replay_pid7184.log)

**Comment by GTIAM** [comment]
We already try to install it with the .exe
It's launch, then close and we have the error log

**Comment by merks** [comment]
That's not surprising given it uses the same JRE.  Try this one:

https://download.eclipse.org/oomph/products/latest/eclipse-inst-jre-win64.exe

It uses 17.0.6 so if that installer works then whatever problem you have in 17.0.4 is fixed...  

Please let me know how that works out either way.

**Comment by GTIAM** [comment]
Thanks, but still the same : 

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc7a338450, pid=3016, tid=3408
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x368450]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows

**Comment by GTIAM** [comment]
We just try another thing : 
download the microsoft jdk 17.06
download eclipse without jre
Try install, 

same error with this "jdk" : 

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc7a19af80, pid=2064, tid=7724

 JRE version: OpenJDK Runtime Environment Microsoft-7209853 (17.0.6+10) (build 17.0.6+10-LTS)
 Java VM: OpenJDK 64-Bit Server VM Microsoft-7209853 (17.0.6+10-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
 Problematic frame:
 V  [jvm.dll+0x36af80]

[hs_err_pid2064.log](https://github.com/eclipse-platform/.github/files/10708999/hs_err_pid2064.log)


Maybe a problem in the computer like the proc ? we read that there were some bugs with C2 processor

**Comment by merks** [comment]
Yes, it seems you have a fundamental problem here unlike any I've ever seen.  Most of these JDKs are based on the same underlying components so it's not surprising that you'd have problems.  Does something as simple as java.exe -version even work?

**Comment by GTIAM** [comment]
> Where? And what is special on "C2" processor", whatever it is?

a lot of website like this: 
https://stackoverflow.com/questions/38663629/eclipse-exception-access-violation-crash
or
https://bugs.openjdk.org/browse/JDK-8154831

We try  something else : 
- uninstall previous openjdk
- install latest : OpenJDK Runtime Environment Temurin-19.0.2+7 
- launcher installer eclipse 202212 without JRE

Same Error : 
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffdce39ccd0, pid=1564, tid=2416

 JRE version: OpenJDK Runtime Environment Temurin-19.0.2+7 (19.0.2+7) (build 19.0.2+7)
 Java VM: OpenJDK 64-Bit Server VM Temurin-19.0.2+7 (19.0.2+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
 Problematic frame:
 V  [jvm.dll+0x3bccd0]

cmd> java -version
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment Temurin-19.0.2+7 (build 19.0.2+7)
OpenJDK 64-Bit Server VM Temurin-19.0.2+7 (build 19.0.2+7, mixed mode, sharing)

Thanks for your help

**Comment by merks** [comment]
I think you'd likely get better help directly from Temurin because they'll know how to read these logs...

https://github.com/adoptium/adoptium-support/issues/new/choose

You should realize that literally millions of people download these installers and packages for use on Windows all using **exactly** this same JRE,  so it can't be the case that this doesn't work generally or even commonly.  It just doesn't work for you specifically, so there must be something unusual about your case that is apparently not a common case.  After all, I work on Windows and it works for me on Windows 10 and my friend has updated to Windows 11 and it works there too...

**Comment by GTIAM** [comment]
Yes, i  posted there. 
It's work on the other PC with win 11 ...

**Comment by jonahgraham** [comment]
The Windows version number reported in the log is 19041 (aka 2004), which was [EOL in Dec 2021](https://learn.microsoft.com/en-us/lifecycle/announcements/windows-10-version-2004-end-of-servicing). However the build number is [2546](https://support.microsoft.com/en-au/topic/january-19-2023-kb5019275-os-builds-19042-2546-19044-2546-and-19045-2546-preview-8ae1b678-d38c-4249-848d-06b722e7c0ad) which is a preview version of Windows. 

Do you have Windows Insider running for this machine?

If so, you may have identified a problem that will be more widely rolled out. Please report this problem to the Insider program so that this doesn't get rolled out wider.

**Comment by jonahgraham** [comment]
BTW the 2546 build was not reported as being release for 19041, maybe because it is EOL anyway. But 2546 was just released in the last couple of weeks, so more users (Windows Insiders only?) may start seeing this in the coming weeks.

**Comment by jonahgraham** [comment]
For those that don't know, you can see all the version info on Windows 10 here https://learn.microsoft.com/en-us/windows/release-health/release-information and the hs_err file has this line to show the running Windows 10 version:

`Host: Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz, 8 cores, 15G,  Windows 10 , 64 bit Build 19041 (10.0.19041.2546)`

**Comment by merks** [comment]
@gdams  Perhaps you have some influence to help ensure that Temurin and Eclipse keep working well on Windows...

**Comment by jukzi** [comment]
closing as error in JDK is not eclipse
